//
//  PersonProtocols.swift
//  Prova
//
//  Created Diego Caridei on 03/08/18.
//  Copyright © 2018 Diego Caridei. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

//MARK: Wireframe -
protocol PersonWireframeProtocol: class {
    static func createModule() -> UIViewController
}
//MARK: Presenter -
protocol PersonPresenterProtocol: class {
    var view: PersonViewProtocol? { get set }
    var wireframe: PersonWireframeProtocol? { get set }
    var interactor: PersonInteractorInputProtocol? { get set }
    func save(person:PersonEntity)
    func viewDidLoad()
}

//MARK: Interactor -
protocol PersonInteractorOutputProtocol: class {
    func didRetrievePeople(_ todos: [PersonEntity])
    /* Interactor -> Presenter */
}

protocol PersonInteractorInputProtocol: class {
    var presenter: PersonInteractorOutputProtocol?  { get set }
    func savePerson(person:PersonEntity)
    func fetchPeople()
    /* Presenter -> Interactor */
}

//MARK: View -
protocol PersonViewProtocol: class {

    var presenter: PersonPresenterProtocol?  { get set }
    func show(people: [PersonEntity])

    /* Presenter -> ViewController */
}
