//
//  PersonInteractor.swift
//  Prova
//
//  Created Diego Caridei on 03/08/18.
//  Copyright © 2018 Diego Caridei. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PersonInteractor: PersonInteractorInputProtocol {
    private var people = [PersonEntity]()
    weak var presenter: PersonInteractorOutputProtocol?
    func savePerson(person:PersonEntity) {
        people.append(person)
    }
    func fetchPeople()  {
        presenter?.didRetrievePeople(self.people)
    }

}
