//
//  PersonRouter.swift
//  Prova
//
//  Created Diego Caridei on 03/08/18.
//  Copyright © 2018 Diego Caridei. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PersonRouter:BaseWireframe, PersonWireframeProtocol {

    weak var viewController: UIViewController?
    static let mainStoryboard = Utils.shared.mainStoryboard

    static func createModule() -> UIViewController {
        let navController = mainStoryboard.instantiateViewController(withIdentifier: "MainNavController")
        guard let view = navController.childViewControllers.first as? PersonViewController else {
            fatalError()
        }
        
        let interactor = PersonInteractor()
        let router = PersonRouter(navigationController: navController as! UINavigationController)
        let presenter = PersonPresenter(interface: view, interactor: interactor, router: router)
        view.presenter = presenter
        interactor.presenter = presenter

        return view
    }
}
